#!/bin/bash

branch="stable"
if [ "$1" == "latest" ]; then
    branch="master"
fi

if test -d "./oxynium"; then
    echo "./oxynium exists and must be deleted before installing"
    exit 1
fi

if [ "$(which nasm)" == "" ]; then
    echo "nasm is not installed"
    exit 1
fi

if [ "$(which gcc)" == "" ]; then
    echo "gcc is not installed"
    exit 1
fi

if [ "$(which cargo)" == "" ]; then
    echo "Cargo is not installed"
    echo 'Please install Rust from https://www.rust-lang.org/tools/install'
fi

git clone -b "$branch" https://github.com/revers3ntropy/oxynium.git
cd oxynium || exit 1

bin/build

if test -d "$HOME/.oxynium"; then
    echo "WARNING: current version of Oxynium will be uninstalled"
fi

echo 'Setting up `~/.oxynium`...'

rm -rf ~/.oxynium
mkdir ~/.oxynium
mkdir ~/.oxynium/bin

mv ./res ~/.oxynium/bin/oxy

if [[ ":$PATH:" == *":$HOME/.oxynium"* ]]; then
  echo "PATH already contains .oxynium dir"
else
  echo 'PATH=$PATH:$HOME/.oxynium/bin' >> ~/.bashrc
fi

cd ..
rm -rf ./oxynium

echo 'Oxynium (`oxy`) has been installed successfully!'
echo 'Run `source ~/.bashrc` or start a new terminal session to use the `oxy` command'
